spring.application.name=Session14-BT03
#Config Datasource
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/db_join_orm_cntt3?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=1234$

#Config Hibernate information
hibernate.show_sql = true 
hibernate.ddl_auto = update
hibernate.dialect = org.hibernate.dialect.MySQLDialect
hibernate.format_sql = true
